name: Update Dojo

on: push

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: pwncollege/dojo-update@v1
        with:
          site: http://pwncollege-dev.arl.madren.org
          dojo: ai~e19112e3
          update_code: ${{ secrets.UPDATE_CODE }}
